from .data_structures import Commands
from .mappers import mst_mapper

no_mapper = lambda response: response

commands_0520: dict[str, Commands] = {  # Commands for the Easy-Driver 0520.
    "reboot": Commands(
        description = (
            "Reboot module. This command is different from the other commands"
            " as the text 'reboot' is not actually sent to the PSU, but rather"
            " a sequence of 9-byte commands via UDP as defined in the"
            " 'reboot_psu' function."
        ),
        is_read = False,
        is_write = True,
        response_mapper = no_mapper,
        unit = None,
        allowed_values = None,
    ),
    "MST": Commands(
        description = "Read module internal status register",
        is_read = True,
        is_write = False,
        response_mapper = mst_mapper,
        unit = None,
        allowed_values = None,
    ),
    "MON": Commands(
        description = "Turn on output driver",
        is_read = False,
        is_write = True,
        response_mapper = no_mapper,
        unit = None,
        allowed_values = None,
    ),
    "MOFF": Commands(
        description = "Turn off output driver",
        is_read = False,
        is_write = True,
        response_mapper = no_mapper,
        unit = None,
        allowed_values = None,
    ),
    "FDB": Commands(
        description = "Feedback command",
        is_read = False,
        is_write = True,
        response_mapper = no_mapper,
        unit = None,
        allowed_values = None,
    ),
    "MRESET": Commands(
        description = "Reset the module status register",
        is_read = False,
        is_write = True,
        response_mapper = no_mapper,
        unit = None,
        allowed_values = None,
    ),
    "MRG": Commands(
        description = "Read selected EEPROM 'value' cell",
        is_read = True,
        is_write = False,
        response_mapper = no_mapper,
        unit = None,
        allowed_values = None,
    ),
    "MRI": Commands(
        description = "Read output current value in amperes. Return the readback value of the power supply actual output current. Current readback values have a 20-bit resolution (19-bit + sign) and they are presented with a 5-digit precision.",
        is_read = True,
        is_write = False,
        response_mapper = no_mapper,
        unit = None,
        allowed_values = None,
    ),
    "MRID": Commands(
        description = "Read module identification",
        is_read = True,
        is_write = False,
        response_mapper = no_mapper,
        unit = None,
        allowed_values = None,
    ),
    "MRM": Commands(
        description = "Set output current value (ramp)",
        is_read = False,
        is_write = True,
        response_mapper = no_mapper,
        unit = None,
        allowed_values = None,
    ),
    "MRP": Commands(
        description = "Read DC-Link voltage value",
        is_read = True,
        is_write = False,
        response_mapper = no_mapper,
        unit = None,
        allowed_values = None,
    ),
    "MRSR": Commands(
        description = "Read current Slew Rate",
        is_read = True,
        is_write = False,
        response_mapper = no_mapper,
        unit = None,
        allowed_values = None,
    ),
    "MRT": Commands(
        description = "Read output stage heatsink temperature",
        is_read = True,
        is_write = False,
        response_mapper = no_mapper,
        unit = None,
        allowed_values = None,
    ),
    "MRTS": Commands(
        description = "Read regulation shunt temperature",
        is_read = True,
        is_write = False,
        response_mapper = no_mapper,
        unit = None,
        allowed_values = None,
    ),
    "MRV": Commands(
        description = "Read output voltage value in volts. Return the readback value of the power supply actual output voltage, measured at the EASY-DRIVER module output terminals. As for the output current, voltage readback values have a 20-bit resolution (19-bit + sign) and they are presented with a 5-digit precision",
        is_read = True,
        is_write = False,
        response_mapper = no_mapper,
        unit = None,
        allowed_values = None,
    ),
    "MVER": Commands(
        description = "Power Supply firmware version",
        is_read = True,
        is_write = False,
        response_mapper = no_mapper,
        unit = None,
        allowed_values = None,
    ),
    "MWG": Commands(
        description = "Write selected EEPROM 'value' cell",
        is_read = False,
        is_write = True,
        response_mapper = no_mapper,
        unit = None,
        allowed_values = None,
    ),
    "MPUP": Commands(
        description = "Reload EEPROM values in DSP",
        is_read = False,
        is_write = True,
        response_mapper = no_mapper,
        unit = None,
        allowed_values = None,
    ),
    "MWSR": Commands(
        description = "Write current Slew Rate in amperes/second. set the value of the ramp slew rate",
        is_read = False,
        is_write = True,
        response_mapper = no_mapper,
        unit = "A/s",
        allowed_values = range(0, 1000+1),
    ),
    "MWI": Commands(
        description = "Set output current value (no ramp)",
        is_read = False,
        is_write = True,
        response_mapper = no_mapper,
        unit = None,
        allowed_values = None,
    ),
}
